# K8s-Diff 규칙 설정 파일

# 제외 규칙 - 이러한 리소스는 비교에서 제외됩니다
exclusion_rules:
  # 시스템 네임스페이스 전체 제외
  - namespace: kube-system
    kind: "*"
    name: "*"
  - namespace: kube-public
    kind: "*"
    name: "*"
  - namespace: kube-node-lease
    kind: "*"
    name: "*"

  # Rancher 관련 네임스페이스
  - namespace: "cattle-*"
    kind: "*"
    name: "*"
  - namespace: "c-*"
    kind: "*"
    name: "*"
  - namespace: "p-*"
    kind: "*"
    name: "*"
  - namespace: "u-*"
    kind: "*"
    name: "*"

  # 특정 리소스 타입 제외
  - namespace: "*"
    kind: Event
    name: "*"
  - namespace: "*"
    kind: EndpointSlice
    name: "*"
  - namespace: "*"
    kind: Lease
    name: "*"
  - namespace: "*"
    kind: Job
    name: "*"

  # 기본 ServiceAccount 제외
  - namespace: "*"
    kind: ServiceAccount
    name: default

  # Istio 관련 제외
  - namespace: istio-system
    kind: "*"
    name: "*"
  - namespace: "*"
    kind: ConfigMap
    name: istio-ca-root-cert
  - namespace: "*"
    kind: ConfigMap
    name: kube-root-ca.crt

  # cert-manager 제외
  - namespace: cert-manager
    kind: "*"
    name: "*"

  # ArgoCD 제외
  - namespace: argocd
    kind: "*"
    name: "*"

  # default-token 시크릿 제외
  - namespace: "*"
    kind: Secret
    name: "default-token-*"

  # VerticalPodAutoscalerCheckpoint 제외
  - namespace: "*"
    kind: VerticalPodAutoscalerCheckpoint
    name: "*"

# 스캔할 리소스 타입
# 비어있으면 모든 리소스 타입을 자동으로 검색합니다 (CRD 포함)
resource_types: []

# 빠른 스캔 모드에서 확인할 중요 리소스
important_resource_types:
  - deployments.apps
  - statefulsets.apps
  - services
  - configmaps
  - secrets
  - ingresses.networking.k8s.io
  - cronjobs.batch

# 스캔에서 제외할 리소스 타입 (하위 리소스 및 메트릭 제외)
skip_resource_types:
  # 하위 리소스 (최상위 리소스에 의해 생성됨)
  - pods
  - replicasets.apps
  - endpoints
  - controllerrevisions.apps

  # 이벤트 및 임시 리소스
  - events
  - events.events.k8s.io
  - endpointslices.discovery.k8s.io

  # 메트릭 리소스 (실시간 데이터)
  - podmetrics.metrics.k8s.io
  - nodemetrics.metrics.k8s.io
  - nodes.metrics.k8s.io
  - pods.metrics.k8s.io

  # API 서비스 관련
  - apiservices.apiregistration.k8s.io
  - aggregatedapirules.apiregistration.k8s.io

  # VPA 관련
  - verticalpodautoscalercheckpoints.autoscaling.k8s.io

# 성능 설정
max_concurrent: 20      # 최대 동시 처리 수
batch_size: 10          # 리소스 타입 배치 크기

# 비교 옵션
compare_resource_contents: false  # 리소스 내용을 해시로 비교할지 여부
strict_api_version: false         # API 버전이 다른 경우 다른 리소스로 처리 (기본: false - Kind만 비교)
